import * as fs from 'node:fs';
import * as path from 'node:path';
import { DEFAULT_MEMWIKI_CONFIG } from '../config/defaults.js';
import { loadRegistry, saveRegistry } from './register.js';

export async function install(opts: { global?: boolean }): Promise<void> {
  const wikiRoot = opts.global
    ? path.join(process.env.HOME || '~', '.memwiki', 'wiki')
    : path.join(process.cwd(), 'wiki');
  const metaDir = path.join(path.dirname(wikiRoot), '.memwiki');

  console.log(`Installing memwiki at ${wikiRoot}...`);

  // Create wiki directories
  const dirs = ['entities', 'topics', 'decisions', 'sessions', 'skills'];
  for (const dir of dirs) {
    fs.mkdirSync(path.join(wikiRoot, dir), { recursive: true });
  }

  // Create index.md if not exists
  const indexPath = path.join(wikiRoot, 'index.md');
  if (!fs.existsSync(indexPath)) {
    fs.writeFileSync(indexPath, `# Project Wiki

Auto-generated by memwiki. Do not edit this file manually.

## Entities
<!-- auto-updated -->

## Recent Sessions
<!-- auto-updated -->
`, 'utf-8');
  }

  // Create log.md if not exists
  const logPath = path.join(wikiRoot, 'log.md');
  if (!fs.existsSync(logPath)) {
    fs.writeFileSync(logPath, `# Wiki Log

| Date | Action | Details |
|------|--------|---------|
`, 'utf-8');
  }

  // Create .memwiki config
  fs.mkdirSync(metaDir, { recursive: true });

  const configPath = path.join(metaDir, 'config.json');
  if (!fs.existsSync(configPath)) {
    fs.writeFileSync(configPath, JSON.stringify({
      ...DEFAULT_MEMWIKI_CONFIG,
      model: process.env.LLM_MODEL || DEFAULT_MEMWIKI_CONFIG.model,
      baseUrl: process.env.LLM_BASE_URL || DEFAULT_MEMWIKI_CONFIG.baseUrl,
    }, null, 2), 'utf-8');
  }

  const statePath = path.join(metaDir, 'state.json');
  if (!fs.existsSync(statePath)) {
    fs.writeFileSync(statePath, JSON.stringify({
      last_ingested_epoch: 0,
      content_hashes: {},
    }, null, 2), 'utf-8');
  }

  const aliasesPath = path.join(metaDir, 'aliases.json');
  if (!fs.existsSync(aliasesPath)) {
    fs.writeFileSync(aliasesPath, '{}', 'utf-8');
  }

  // Update .gitignore
  const gitignorePath = path.join(process.cwd(), '.gitignore');
  const gitignoreEntry = '\n# memwiki\n.memwiki/\n';
  if (fs.existsSync(gitignorePath)) {
    const existing = fs.readFileSync(gitignorePath, 'utf-8');
    if (!existing.includes('.memwiki/')) {
      fs.appendFileSync(gitignorePath, gitignoreEntry, 'utf-8');
    }
  } else {
    fs.writeFileSync(gitignorePath, gitignoreEntry.trim() + '\n', 'utf-8');
  }

  console.log(`Done! Wiki initialized at ${wikiRoot}`);

  // Auto-register if ~/.memwiki/projects.json exists (multi-repo mode)
  if (!opts.global) {
    const HOME = process.env.HOME || process.env.USERDIR || '~';
    const registryPath = path.join(HOME, '.memwiki', 'projects.json');
    if (fs.existsSync(registryPath)) {
      try {
        const registry = loadRegistry();
        const projectPath = process.cwd();
        const name = path.basename(projectPath);
        const wikiDir = path.join(projectPath, 'wiki');

        let pagesCount = 0;
        const dirs = ['entities', 'topics', 'decisions', 'sessions', 'skills'];
        for (const dir of dirs) {
          const dirPath = path.join(wikiDir, dir);
          if (!fs.existsSync(dirPath)) continue;
          pagesCount += fs.readdirSync(dirPath).filter(f => f.endsWith('.md')).length;
        }

        registry.projects[name] = {
          path: projectPath,
          registered_at: registry.projects[name]?.registered_at || new Date().toISOString(),
          last_ingest: registry.projects[name]?.last_ingest || null,
          observations_count: registry.projects[name]?.observations_count || 0,
          pages_count: pagesCount,
        };

        saveRegistry(registry);
        console.log(`Auto-registered project "${name}" in multi-repo registry.`);

        // Create symlink
        const projectsDir = path.join(HOME, '.memwiki', 'projects');
        const linkPath = path.join(projectsDir, name);
        const linkTarget = path.join(projectPath, '.memwiki');
        fs.mkdirSync(projectsDir, { recursive: true });
        if (fs.existsSync(linkPath)) fs.rmSync(linkPath, { force: true });
        try {
          fs.symlinkSync(linkTarget, linkPath, 'dir');
        } catch { /* ignore symlink errors */ }
      } catch (err: any) {
        // Non-critical: don't fail install if auto-register fails
        console.warn(`Warning: auto-register failed: ${err.message}`);
      }
    }
  }

  console.log(`Next steps:`);
  console.log(`  1. Run a Claude Code session (claude-mem will capture observations)`);
  console.log(`  2. Run "memwiki ingest" to promote observations to wiki pages`);
  console.log(`  3. Run "memwiki context" to see wiki summary for next session`);
}
