import * as fs from 'node:fs';
import * as path from 'node:path';

export async function install(opts: { global?: boolean }): Promise<void> {
  const wikiRoot = opts.global
    ? path.join(process.env.HOME || '~', '.memwiki', 'wiki')
    : path.join(process.cwd(), 'wiki');
  const metaDir = path.join(path.dirname(wikiRoot), '.memwiki');

  console.log(`Installing memwiki at ${wikiRoot}...`);

  // Create wiki directories
  const dirs = ['entities', 'topics', 'decisions', 'sessions', 'skills'];
  for (const dir of dirs) {
    fs.mkdirSync(path.join(wikiRoot, dir), { recursive: true });
  }

  // Create index.md if not exists
  const indexPath = path.join(wikiRoot, 'index.md');
  if (!fs.existsSync(indexPath)) {
    fs.writeFileSync(indexPath, `# Project Wiki

Auto-generated by memwiki. Do not edit this file manually.

## Entities
<!-- auto-updated -->

## Recent Sessions
<!-- auto-updated -->
`, 'utf-8');
  }

  // Create log.md if not exists
  const logPath = path.join(wikiRoot, 'log.md');
  if (!fs.existsSync(logPath)) {
    fs.writeFileSync(logPath, `# Wiki Log

| Date | Action | Details |
|------|--------|---------|
`, 'utf-8');
  }

  // Create .memwiki config
  fs.mkdirSync(metaDir, { recursive: true });

  const configPath = path.join(metaDir, 'config.json');
  if (!fs.existsSync(configPath)) {
    fs.writeFileSync(configPath, JSON.stringify({
      model: 'openrouter/elephant-alpha',
      baseUrl: 'https://openrouter.ai/api/v1',
      claudeMemUrl: 'http://127.0.0.1:37777',
      maxTokens: 4096,
    }, null, 2), 'utf-8');
  }

  const statePath = path.join(metaDir, 'state.json');
  if (!fs.existsSync(statePath)) {
    fs.writeFileSync(statePath, JSON.stringify({
      last_ingested_epoch: 0,
      content_hashes: {},
    }, null, 2), 'utf-8');
  }

  const aliasesPath = path.join(metaDir, 'aliases.json');
  if (!fs.existsSync(aliasesPath)) {
    fs.writeFileSync(aliasesPath, '{}', 'utf-8');
  }

  // Update .gitignore
  const gitignorePath = path.join(process.cwd(), '.gitignore');
  const gitignoreEntry = '\n# memwiki\n.memwiki/\n';
  if (fs.existsSync(gitignorePath)) {
    const existing = fs.readFileSync(gitignorePath, 'utf-8');
    if (!existing.includes('.memwiki/')) {
      fs.appendFileSync(gitignorePath, gitignoreEntry, 'utf-8');
    }
  } else {
    fs.writeFileSync(gitignorePath, gitignoreEntry.trim() + '\n', 'utf-8');
  }

  console.log(`Done! Wiki initialized at ${wikiRoot}`);
  console.log(`Next steps:`);
  console.log(`  1. Run a Claude Code session (claude-mem will capture observations)`);
  console.log(`  2. Run "memwiki ingest" to promote observations to wiki pages`);
  console.log(`  3. Run "memwiki context" to see wiki summary for next session`);
}
